<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Filtrera_project-link-1</name>
   <tag></tag>
   <elementGuidId>2ce8ca91-ee10-4f62-89e3-50fd893503ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#project-link-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='project-link-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d0e641d2-aa0a-42cb-9370-5761cdae969a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>scroll-position image-inner lazy-load b-error b-error lazy-loaded</value>
      <webElementGuid>b88b828a-0fbb-4189-8825-532017015ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>project-link-1</value>
      <webElementGuid>8d6e37b2-9b76-425e-b097-407929cfbd6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;project-link-1&quot;)</value>
      <webElementGuid>04dea233-30f6-41b5-a2dc-f421e3c792ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='project-link-1']</value>
      <webElementGuid>84af9178-9be1-422a-a2c7-3a08ebc97221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-projects']/div/div/div/a/div</value>
      <webElementGuid>41baa9e0-ded7-4dc3-84fe-6ef3d04ead58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a/div</value>
      <webElementGuid>a7db8337-a9f7-4636-92f7-8887f1b43b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'project-link-1']</value>
      <webElementGuid>52fe0139-2744-4c01-a3b4-9fe61eedd891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
