<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sk_accommodation-searchblock-autocomp_945b91</name>
   <tag></tag>
   <elementGuidId>2032aa77-b2ba-4573-b6bb-a2ec0c0d92a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accommodation-searchblock-autocomplete-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accommodation-searchblock-autocomplete-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0402c98-fbf2-4ace-8afd-6e7335591d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e23a5d37-3488-4134-a394-ccf9807829ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Län, kommun, stad, gata eller projektnamn</value>
      <webElementGuid>347a5c48-ec00-4670-8441-b51cef9d4bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accommodation-searchblock-autocomplete-input</value>
      <webElementGuid>d2b339da-f9ed-4274-8bc1-490e6396ea67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focused</value>
      <webElementGuid>61d71eca-b3d5-4bab-9d4d-693a94f33073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accommodation-searchblock-autocomplete-input&quot;)</value>
      <webElementGuid>44051adb-61e3-4503-9079-e3a5e4e65635</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accommodation-searchblock-autocomplete-input']</value>
      <webElementGuid>097a43d8-f254-48fd-b671-21c64b9cf73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Sok-bostad']/div[2]/div/div/div/div/div/div/div/div/fieldset/input</value>
      <webElementGuid>2bdbc9f1-ddad-4a73-95f9-9bf9daafa711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>7aa0c8f8-1c81-4b4f-a670-d09ae24e366b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Län, kommun, stad, gata eller projektnamn' and @id = 'accommodation-searchblock-autocomplete-input']</value>
      <webElementGuid>856158a5-ce98-4114-901c-ef61b973ab0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
