<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bostder (33)</name>
   <tag></tag>
   <elementGuidId>faeb0a5e-c5e4-453f-9ded-3335ff62a610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-accommodations-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-accommodations-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9c38c1e-e3dd-45cc-b18f-a7191fd0c012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link active</value>
      <webElementGuid>fb7a2689-5760-403f-a805-f7409e15ce27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-accommodations-tab</value>
      <webElementGuid>45c67254-15e8-4ed7-89de-f725b083d3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6b09577f-dd63-4702-9f40-155ac983c786</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#nav-accommodations</value>
      <webElementGuid>22fac225-6184-443f-84cd-f28bc0a069d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#nav-accommodations</value>
      <webElementGuid>73a078d5-e8c5-4051-91cc-032fa67d3e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>11322c45-2f65-42aa-8536-5c3df6a23fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>nav-accommodations</value>
      <webElementGuid>4b67f295-9c10-4e41-b0ba-563f44447c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c977a61-90b0-4b02-b261-51b998a8debe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bostäder (33)</value>
      <webElementGuid>2bfde245-8718-42dd-a7ab-d63f4d2a6717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-accommodations-tab&quot;)</value>
      <webElementGuid>ac8f7bd8-09b1-4899-87e4-695b280b672b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-accommodations-tab']</value>
      <webElementGuid>0b2c212b-28de-4418-aa5f-20d75802bd67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tab']/a</value>
      <webElementGuid>aeb429b4-9c0d-437e-9405-8b7c1e4825f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aktiva'])[1]/following::a[1]</value>
      <webElementGuid>b9ba7ba0-33ea-4306-8d33-0d0c4687e9d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bostäder (']/parent::*</value>
      <webElementGuid>8fbbc6a9-e8af-4e53-aa95-17c53f1fd714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#nav-accommodations')]</value>
      <webElementGuid>ce31b8ec-1cb1-461a-8c21-dcc6a5060233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/nav/div/a</value>
      <webElementGuid>ea2d0b17-f823-44b1-8591-70cf01a22e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-accommodations-tab' and @href = '#nav-accommodations' and (text() = 'Bostäder (33)' or . = 'Bostäder (33)')]</value>
      <webElementGuid>8ce40d43-4a9f-437a-8238-ba64bd927e95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
