<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Projekt (9)</name>
   <tag></tag>
   <elementGuidId>e6c7d6d5-2935-4335-b3fc-706e9c6c994f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nav-projects-tab</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-projects-tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ad8d5daf-e6ae-45ff-b232-c8fc9520f611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link active</value>
      <webElementGuid>42f696a0-a6a0-481c-b219-5de5f4122118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-projects-tab</value>
      <webElementGuid>41a9c3ee-f7b5-462c-bf95-ca9b75418d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9d3a8538-9f18-42ed-aa7c-b484ff7791bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#nav-projects</value>
      <webElementGuid>726bc04a-8f5e-4ac7-a459-2525f2c1b61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#nav-projects</value>
      <webElementGuid>c5db6162-5f4d-49cb-869c-b880ac20b1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>55693c2c-aa32-4a27-a97e-2ead94da02c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>nav-projects</value>
      <webElementGuid>60483ce3-0ded-40cd-92c3-950b6bf606b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7ad712fb-1076-49ba-b1cf-39068330c34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Projekt (9)</value>
      <webElementGuid>25ccc9fe-c254-4566-9a3e-9edcd4a7b6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-projects-tab&quot;)</value>
      <webElementGuid>2429a665-db12-4162-bd61-8ed44ab46135</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-projects-tab']</value>
      <webElementGuid>54c4e0c6-35b5-4903-b95e-8261b6c4e3d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nav-tab']/a[2]</value>
      <webElementGuid>763dedde-ae23-40fd-80ba-4a2d197b28e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='aktiva'])[1]/following::a[2]</value>
      <webElementGuid>c28ecaa5-cbd4-47da-8dc5-d3fc1effb4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Projekt (']/parent::*</value>
      <webElementGuid>4479a884-7b48-4f08-b480-bd40842647d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#nav-projects')]</value>
      <webElementGuid>8bcd6390-2958-42cc-8a1e-c68253d3bac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/a[2]</value>
      <webElementGuid>1be7ac43-2188-45cd-a14c-12cd45b5a7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-projects-tab' and @href = '#nav-projects' and (text() = 'Projekt (9)' or . = 'Projekt (9)')]</value>
      <webElementGuid>547b5ce1-5132-4e6b-ae41-4563ec82eb28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
