<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sk</name>
   <tag></tag>
   <elementGuidId>f07f7a56-b30b-4854-b321-410eb192a940</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit-accommodation-hero-search-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit-accommodation-hero-search-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f95d0fe7-4121-4478-b535-7ef6a01ded6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64676715-5ce5-4066-8e76-222416974d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>73e1db5d-c003-488c-b113-e06ff74605c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submit-accommodation-hero-search-button</value>
      <webElementGuid>92e36d14-7f1b-48eb-9cb6-bf49634a6ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sök</value>
      <webElementGuid>ea578773-803f-4f98-a6ee-9fc1789a4247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit-accommodation-hero-search-button&quot;)</value>
      <webElementGuid>ace6cfd7-3157-4b96-a7ce-02135db36af8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submit-accommodation-hero-search-button']</value>
      <webElementGuid>0456bf75-fe4f-456c-9ebe-8af288741582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Sok-bostad']/div[2]/div/div/div/div/div/div/div/div/fieldset/button</value>
      <webElementGuid>0c069266-fe22-4847-9d69-4f4b5e307351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sök bostad i'])[1]/following::button[1]</value>
      <webElementGuid>646676ce-12c5-4888-b4c8-afedd9c03d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sök nya bostäder'])[1]/following::button[1]</value>
      <webElementGuid>2ee9fd1c-ed6d-40a9-86d2-5105a5ad451b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='visa filter'])[1]/preceding::button[1]</value>
      <webElementGuid>6cf42e60-e8a2-4360-9a5e-9f9d1c351b15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dölj filter'])[1]/preceding::button[1]</value>
      <webElementGuid>ad9a89a6-38f1-446e-8b8a-67672a06c7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8618a381-5487-48e2-b03c-271849b3a76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'submit-accommodation-hero-search-button' and (text() = 'Sök' or . = 'Sök')]</value>
      <webElementGuid>cd75e04d-5f9a-4528-884c-3f492a2c7a03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
