<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sk_accommodation-searchblock-autocomp_945b91</name>
   <tag></tag>
   <elementGuidId>5b347eee-6b75-4fa8-89b3-1c01889338ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accommodation-searchblock-autocomplete-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='accommodation-searchblock-autocomplete-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eec078a-3b55-462d-a3f9-335ec1086469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c06bcc61-e414-4ae2-aa30-bdfbb697d3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Län, kommun, stad, gata eller projektnamn</value>
      <webElementGuid>8f8360c9-0181-4f06-b2f0-4ffaf9a9c679</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accommodation-searchblock-autocomplete-input</value>
      <webElementGuid>1a5baa55-56ab-4746-b3e0-099eb981c8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accommodation-searchblock-autocomplete-input&quot;)</value>
      <webElementGuid>48ce21db-4842-4916-b576-7f318a9c7f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='accommodation-searchblock-autocomplete-input']</value>
      <webElementGuid>ec697cd6-0532-41df-83d5-5b9d04a7b23b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='Sok-bostad']/div[2]/div/div/div/div/div/div/div/div/fieldset/input</value>
      <webElementGuid>6d2c0e78-2b15-4795-9b99-1fd1a4faa47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>c49f62f5-79a2-467a-aaf5-bb9cdadc5dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Län, kommun, stad, gata eller projektnamn' and @id = 'accommodation-searchblock-autocomplete-input']</value>
      <webElementGuid>fb7e8a2a-c4db-4ead-8f5d-8ab413031a45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
