<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bostadsvljare</name>
   <tag></tag>
   <elementGuidId>9941249c-0ea6-46ed-b9ac-c4271f887efb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div/div/nav/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>730ec074-4458-4f7c-ab75-901904da9d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#bostadsvaljare</value>
      <webElementGuid>2c550bc3-0526-4b16-8971-1258b34d13fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-anchor</value>
      <webElementGuid>e1ae6576-13ff-44f6-9f9e-148f4624854c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bostadsväljare</value>
      <webElementGuid>b591c118-ce0b-4f5d-9f01-d2c3d8471685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;js-sticky-container&quot;]/div[@class=&quot;accommodation-anchor-navigation js-sticky-floating&quot;]/nav[@class=&quot;inline container js-scroll-container shadow-right&quot;]/ul[1]/li[@class=&quot;d-inline-block&quot;]/a[@class=&quot;menu-anchor&quot;]</value>
      <webElementGuid>9e168fb6-6a07-4dea-aa36-331ed382938e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>c5cbe131-b85e-461d-bec2-fa0d9beeb1d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bostadsväljare')]</value>
      <webElementGuid>ee26cdba-c4cf-489a-a491-5b0e762dfbc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Om bostäderna'])[1]/following::a[1]</value>
      <webElementGuid>8019231a-f36d-43c4-b3ab-6ba214940972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bilder'])[1]/following::a[2]</value>
      <webElementGuid>cb5ec8c1-bd5f-49cb-93b3-7300a56b632f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontakt'])[1]/preceding::a[1]</value>
      <webElementGuid>18cc2df1-226b-4b90-8ef2-754b83c1a2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anmäl intresse'])[1]/preceding::a[2]</value>
      <webElementGuid>95ec0180-da07-4377-ad4c-c6b5948290b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bostadsväljare']/parent::*</value>
      <webElementGuid>658d2211-2061-40d7-a479-0d7e52c41b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#bostadsvaljare')]</value>
      <webElementGuid>4b20bcf2-0692-407e-bdd6-bcf1d2d213fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>f0789867-5ae9-4588-bce2-77be7f5ac9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#bostadsvaljare' and (text() = 'Bostadsväljare' or . = 'Bostadsväljare')]</value>
      <webElementGuid>03fb803e-ca56-439b-9d22-536290e527b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
