<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Visningar</name>
   <tag></tag>
   <elementGuidId>13feb17e-5f8b-4136-a0ec-98a69f9eb309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.menu-anchor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div/div/nav/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d7e9abd-9d5a-4e8d-9d71-20335545db54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#visningar</value>
      <webElementGuid>9d26a4d8-cf4d-44b8-bab8-0b99d628f3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-anchor</value>
      <webElementGuid>1080fa66-e7e8-41c1-aeca-92ea9edbdadc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Visningar</value>
      <webElementGuid>dd1aa8d2-32c7-4d8f-907f-fd2385637fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;js-sticky-container&quot;]/div[@class=&quot;accommodation-anchor-navigation js-sticky-floating&quot;]/nav[@class=&quot;inline container js-scroll-container shadow-right&quot;]/ul[1]/li[@class=&quot;d-inline-block&quot;]/a[@class=&quot;menu-anchor&quot;]</value>
      <webElementGuid>a6cad79f-c6ff-4dbe-bebd-25dff9d23b31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/nav/ul/li/a</value>
      <webElementGuid>0cbcae19-09d2-4dba-af21-04428db48178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Visningar')]</value>
      <webElementGuid>a99112c8-5a38-4624-bb4a-cfe50bf98013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brf Cykelverkstaden'])[1]/following::a[2]</value>
      <webElementGuid>843dcda6-1b87-4cc4-83d5-74641d76c1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bilder'])[1]/preceding::a[1]</value>
      <webElementGuid>af68b5fb-9189-4e71-8b8e-57c580752844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Om bostäderna'])[1]/preceding::a[2]</value>
      <webElementGuid>03f134f6-0575-4bef-a653-d66b82459215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Visningar']/parent::*</value>
      <webElementGuid>012a4851-a8db-4e43-b800-e71fce144150</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#visningar')]</value>
      <webElementGuid>633cbd5e-1982-4374-ad92-270413a669b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/nav/ul/li/a</value>
      <webElementGuid>c065a5f2-223f-483e-aec4-b35d27cc981a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#visningar' and (text() = 'Visningar' or . = 'Visningar')]</value>
      <webElementGuid>92cb0885-e74c-4b0a-9968-fa6bc12c5d76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
