<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anml intresse</name>
   <tag></tag>
   <elementGuidId>de6c482c-7384-4a11-8d58-01b86f7a8d7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div[2]/div/div/div/div/div/div/div/div/div/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>36758ede-d35e-483c-8c80-0039c3e02609</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>large</value>
      <webElementGuid>d5945bef-49e8-460a-b76d-cb4e5095e827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/ny-bostad/aktuella-projekt/stockholm/bjorkhagen/</value>
      <webElementGuid>322ed20e-28ea-4582-9fac-192ddf086289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Anmäl intresse Björkhagen</value>
      <webElementGuid>75e456b1-cc5b-4331-9b6b-4cb8d409b319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anmäl intresse</value>
      <webElementGuid>98a65c76-bb38-4e52-9816-ffac3c630a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row row0 equal-height&quot;]/div[@class=&quot;block contentblocklist       col-12&quot;]/div[@class=&quot;bg-white text-gray-87&quot;]/div[@class=&quot;container content-blocklist-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;full-width&quot;]/div[@class=&quot;row row0 equal-height&quot;]/div[@class=&quot;block projectpage       col-12 displaymode-full&quot;]/div[@class=&quot;card eq-block text-gray-87 project-display&quot;]/div[@class=&quot;card-body&quot;]/a[@class=&quot;large&quot;]</value>
      <webElementGuid>10f2e416-b7d9-4ef5-b7a5-36a78278c3d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div[2]/div/div/div/div/div/div/div/div/div/div/div/a[2]</value>
      <webElementGuid>1f5bf39d-5712-452d-8001-12f3706e8f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Anmäl intresse')]</value>
      <webElementGuid>2764d490-d1e1-4317-bc4e-3ec53dfcc631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Björkhagen'])[1]/following::a[1]</value>
      <webElementGuid>ef14f4fb-2fc8-4a74-acb4-b0eb0e1007b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Klimatsmart kvarter för familjer'])[1]/following::a[1]</value>
      <webElementGuid>02aa5c40-faaa-43fe-9f42-92dcd4205ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bostadsrätter i Stockholm med omnejd'])[1]/preceding::a[1]</value>
      <webElementGuid>ad7488c2-bf0e-45e6-926e-58cc9adc2ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Våra bostäder i Stockholmsområdet'])[1]/preceding::a[1]</value>
      <webElementGuid>673ce55a-5ecb-434e-a786-bc75ca1cf22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anmäl intresse']/parent::*</value>
      <webElementGuid>a210533a-60c1-4005-a3d7-15b82a98819c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/ny-bostad/aktuella-projekt/stockholm/bjorkhagen/')])[3]</value>
      <webElementGuid>0ed84ab9-147e-4571-9619-50240c2a597f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a[2]</value>
      <webElementGuid>add5854b-b6dc-464c-8e68-c66aa01d8348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/ny-bostad/aktuella-projekt/stockholm/bjorkhagen/' and (text() = 'Anmäl intresse' or . = 'Anmäl intresse')]</value>
      <webElementGuid>33cf2a93-bd2d-4c6e-8cbf-bdc1bc82d52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
