<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Anml intresse_1</name>
   <tag></tag>
   <elementGuidId>f1901224-fd4d-4fda-aa2b-a83b7b45fd73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main-content']/div/div/nav/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.menu-interest.menu-anchor.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>006dac2e-a13d-4691-b528-bbc50748f052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#anmal-intresse</value>
      <webElementGuid>2a499276-942e-4b03-8c73-7f9611138736</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-interest menu-anchor btn btn-primary</value>
      <webElementGuid>952cd3eb-ee55-401d-b9ea-55fad0046461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anmäl intresse</value>
      <webElementGuid>fa85a706-799a-47a9-a952-9d63379f1f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;js-sticky-container&quot;]/div[@class=&quot;accommodation-anchor-navigation js-sticky-floating&quot;]/nav[@class=&quot;inline container js-scroll-container shadow-right&quot;]/ul[1]/li[@class=&quot;menu-interest d-none d-lg-block&quot;]/a[@class=&quot;menu-interest menu-anchor btn btn-primary&quot;]</value>
      <webElementGuid>e68c5d8b-975c-487c-b90a-a24a3ef126fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>f22cb1ca-7ae8-4324-9b26-0695ead998b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Anmäl intresse')]</value>
      <webElementGuid>fd9c6c4a-eb81-4825-bcdb-4233070651a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kontakt'])[1]/following::a[1]</value>
      <webElementGuid>6bbfc8ca-e6c5-4544-b2a7-fd02f42838ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Om bostäderna'])[1]/following::a[2]</value>
      <webElementGuid>41c8972d-b1ce-4d8b-b792-0dca8798f03b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anmäl intresse'])[2]/preceding::a[1]</value>
      <webElementGuid>b9fac906-e547-4bda-8e7c-cf82c1f72557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stäng'])[1]/preceding::a[2]</value>
      <webElementGuid>15e739f0-1fa5-426a-8211-bc4b92588649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anmäl intresse']/parent::*</value>
      <webElementGuid>3d18b8e0-edab-4ebe-85bf-9f3b60e9aaac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#anmal-intresse')]</value>
      <webElementGuid>80bbbbeb-4dca-4393-be0f-5e6ac4345c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/nav/ul/li[4]/a</value>
      <webElementGuid>4e1e8924-7c51-4033-acff-f76347551374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#anmal-intresse' and (text() = 'Anmäl intresse' or . = 'Anmäl intresse')]</value>
      <webElementGuid>e7304582-32bf-46c4-97f8-dc9c90a28e5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
