<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personnummer (mmddxxxx)_personal-number</name>
   <tag></tag>
   <elementGuidId>2a79d575-7159-40a8-855d-311d07ad6b48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='personal-number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#personal-number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33b1b785-e9ca-413c-9d91-791bfc4a8a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9898bf7a-6206-48b2-8409-63d5ca3c8d05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>personal-number</value>
      <webElementGuid>f39e0442-4373-4f59-8c19-1018fb22408e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(19|20)[0-9]{6}[- ]?[0-9]{4}$</value>
      <webElementGuid>388b22d2-b8e1-4822-8d19-d19418f1c903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;personal-number&quot;)</value>
      <webElementGuid>7f50ce5e-2fa9-481a-a259-f73ea67ae2af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='personal-number']</value>
      <webElementGuid>2b03e46a-0866-4317-860a-0cd43919540d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='anmal-intresse']/div/div[2]/div[2]/form/div/div/fieldset/input</value>
      <webElementGuid>611044c1-fa4e-4a2b-b445-f65d81bd170e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/input</value>
      <webElementGuid>5e44d918-98b6-49b3-b1ae-dab30b1cc2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'personal-number']</value>
      <webElementGuid>05441b6a-edfc-4bb9-8b1c-121466380a81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
